version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:java8
    container_name: minecraft-paper-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.16.5"
      MEMORY: "2G"
      SERVER_NAME: "Paper Minecraft Server"
      MOTD: "Welcome to Paper Minecraft Server 1.16.5!"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "20"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "false"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      MAX_BUILD_HEIGHT: "256"
      MAX_TICK_TIME: "60000"
      ONLINE_MODE: "false"
      PVP: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      VIEW_DISTANCE: "10"
      SEED: ""
      MODE: "survival"
      LEVEL: "world"
    volumes:
      - minecraft_data:/data
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  minecraft_data:
    driver: local